#!/usr/bin/env bash
# AUTH: codenvibes
# a Bash script that sets up Nginx web server with basic "Hello World!" page

sudo apt- update -y
sudo apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
