#!/usr/bin/env bash
# AUTH: codenvibes
# a Bash script that sets up Nginx web server with basic "Hello World!" page

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello, world!" | sudo tee /var/www/html/index.html
sudo service nginx restart
