#!/usr/bin/env bash
# AUTH: codenvibes
# DESC: A bash script for adding a custom 404 page ("Ceci n'est pas une page") to Nginx configuration

sudo apt update
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.html
rdrct='server_name _;\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;'
sed -i "s|server_name\s*_;|$rdrct|" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
err_pg="listen [::]:80 default_server;\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sed -i "s|listen \[::\]:80 default_server;|$err_pg|" /etc/nginx/sites-available/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
