#!/usr/bin/env bash
# AUTH: codenvibes
# DESC: A bash script for adding a custom 404 page ("Ceci n'est pas une page") to Nginx configuration

sudo apt update
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i '/server_name _;/a \
    error_page 404 /404.html;\n\
    location = /404.html {\n\
        internal;\n\
    }' /etc/nginx/sites-available/default
sudo service nginx start
