#!/usr/bin/env bash
# AUTH: codenvibes
# DESC: This script configures HAProxy as a load balancer.
#       It updates the package list, installs required packages,
#       adds the HAProxy repository, installs HAProxy 2.0,
#       and configures the load balancing with two backend servers.

# Update the package list 
sudo apt-get -y update
# Install required packages
sudo apt-get -y install software-properties-common
# Add the HAProxy repository and install HAProxy 2.0
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy
# HAProxy configuration
