#!/usr/bin/env bash
# AUTH: codenvibes
# Remove the default Nginx site configuration from sites-enabled
rm /etc/nginx/sites-enabled/default
# Create a symbolic link to the default Nginx site configuration
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restart the Nginx service to apply the changes
service nginx restart
