#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes.
i=1
while [ $i -le 12 ]
do
	a=1
	while [ $a -le 60 ]
	do
		if [ $a == 60 ]
		then
			echo "Hour: "$i
		else
			echo $a
		fi
		((a++))
	done
	((i++))
done
